# Generated by Django 2.1 on 2018-08-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activebuzzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_activebuzzer', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='aroadtracing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_aroadtracing', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('current_value', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dht11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpi_code', models.CharField(max_length=20)),
                ('rpi_name', models.CharField(max_length=20)),
                ('remote_serverhost', models.CharField(max_length=20)),
                ('remote_serverport', models.IntegerField()),
                ('local_serverhost', models.CharField(max_length=20)),
                ('local_serverport', models.IntegerField()),
                ('local_servermaxconcount', models.IntegerField()),
                ('local_clientcount', models.IntegerField()),
                ('sendtime', models.IntegerField()),
                ('checkcontime', models.IntegerField()),
                ('equipmentInfos', models.CharField(max_length=255, null=True)),
                ('equipmentkey', models.CharField(max_length=255, null=True)),
                ('r1', models.CharField(max_length=255, null=True)),
                ('r2', models.CharField(max_length=255, null=True)),
                ('create_time', models.DateTimeField()),
                ('remark', models.CharField(max_length=200, null=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_fire', models.IntegerField()),
                ('fire_value', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_human', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='infraredemission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_infraredemission', models.IntegerField()),
                ('infraredemission_value', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='infraredreception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_infraredreception', models.IntegerField()),
                ('infraredreception_value', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='led',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_led', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_light', models.IntegerField()),
                ('light_value', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='obstacleavoidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_obstacleavoidance', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('wPi', models.IntegerField()),
                ('BCM', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='propertymapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=20)),
                ('property_value', models.CharField(max_length=20)),
                ('property_meaning', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_rain', models.IntegerField()),
                ('rain_value', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_relay', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpi_code', models.CharField(max_length=20)),
                ('sensor_code', models.CharField(max_length=3)),
                ('sensor_name', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
                ('acqfre', models.FloatField()),
                ('tranfre', models.FloatField()),
                ('enable', models.IntegerField()),
                ('keep_time', models.IntegerField()),
                ('rediscount', models.IntegerField()),
                ('pins', models.CharField(max_length=50)),
                ('parameters', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField()),
                ('remark', models.CharField(max_length=200, null=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='smoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_smoke', models.IntegerField()),
                ('smoke_value', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_soil', models.IntegerField()),
                ('soil_value', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('is_sound', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ultrasonic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=3)),
                ('distance', models.FloatField()),
                ('create_time', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
